const puzzleData = [
  {
    id: 1,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'pešiakové',
    difficulty: 'ľahké',
    img: './images/chess9.jpg',
  },
  {
    id: 2,
    title: 'Čierny na ťahu',
    tahy: 3,
    category: 'strelcové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 3,
    title: 'Čierny na ťahu',
    tahy: 3,
    category: 'pešiakové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 4,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'vežové',
    difficulty: 'ťažké',
    img: './images/chess9.jpg',
  },
  {
    id: 5,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'pešiakové',
    difficulty: 'ťažké',
    img: './images/chess9.jpg',
  },
  {
    id: 6,
    title: 'Čierny na ťahu',
    tahy: 3,
    category: 'pešiakové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 7,
    title: 'Čierny na ťahu',
    tahy: 3,
    category: 'vežové',
    difficulty: 'ťažké',
    img: './images/chess9.jpg',
  },
  {
    id: 8,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'dámové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 9,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'pešiakové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 10,
    title: 'Čierny na ťahu',
    tahy: 3,
    category: 'dámové',
    difficulty: 'ťažké',
    img: './images/chess9.jpg',
  },
  {
    id: 11,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'vežové',
    difficulty: 'ťažké',
    img: './images/chess9.jpg',
  },
  {
    id: 12,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'pešiakové',
    difficulty: 'ťažké',
    img: './images/chess9.jpg',
  },
  {
    id: 13,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'vežové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 14,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'pešiakové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 15,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'dámové',
    difficulty: 'ťažké',
    img: './images/chess9.jpg',
  },
  {
    id: 16,
    title: 'Čierny na ťahu',
    tahy: 3,
    category: 'jazdcové',
    difficulty: 'ťažké',
    img: './images/chess9.jpg',
  },
  {
    id: 17,
    title: 'Čierny na ťahu',
    tahy: 3,
    category: 'pešiakové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 18,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'vežové',
    difficulty: 'ťažké',
    img: './images/chess9.jpg',
  },
  {
    id: 19,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'strelcové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 20,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'jazdcové',
    difficulty: 'ťažké',
    img: './images/chess9.jpg',
  },
  {
    id: 21,
    title: 'Čierny na ťahu',
    tahy: 3,
    category: 'pešiakové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 22,
    title: 'Čierny na ťahu',
    tahy: 3,
    category: 'dámové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 23,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'vežové',
    difficulty: 'ľahké',
    img: './images/chess9.jpg',
  },
  {
    id: 24,
    title: 'Čierny na ťahu',
    tahy: 3,
    category: 'jazdcové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 25,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'strelcové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 26,
    title: 'Čierny na ťahu',
    tahy: 3,
    category: 'dámové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
  {
    id: 27,
    title: 'Biely na ťahu',
    tahy: 3,
    category: 'vežové',
    difficulty: 'stredné',
    img: './images/chess9.jpg',
  },
]

export default puzzleData
